In [5]:
import pickle 
import pandas as pd

In [2]:
baseline=pickle.load(open("../interpret/K562.DNASE.baseline.fold0.deepSHAP",'rb'))

In [3]:
corrected=pickle.load(open("../interpret/K562.DNASE.bias_corrected_bpnet_tobias.fold0.deepSHAP",'rb'))

In [4]:
unplugged=pickle.load(open("../interpret/K562.DNASE.bias_corrected_bpnet_tobias.unplugged.fold0.deepSHAP",'rb'))

In [6]:
baseline.keys()

dict_keys(['label_prof', 'label_sum', 'pred_prof', 'pred_sum', 'profile_shap', 'count_shap', 'seq'])

In [7]:
def extract_region(region,interp_dict):
    label_prof=interp_dict['label_prof'][region]
    label_sum=round(interp_dict['label_sum'][region],3)
    pred_prof=interp_dict['pred_prof'][region]
    pred_sum=round(interp_dict['pred_sum'][region],3)
    profile_shap=interp_dict['profile_shap'][region][173:173+1000]
    count_shap=interp_dict['count_shap'][region][173:173+1000]
    seq=interp_dict['seq'][region][173:173+1000]
    profile_shap=profile_shap*seq 
    count_shap=count_shap*seq 
    #get the min & max values, to use in ylims for plotting 
    minval_perf=min([label_prof.min(),pred_prof.min()])
    maxval_perf=max([label_prof.max(),pred_prof.max()])
    minval_shap=min([profile_shap.min(), count_shap.min()])
    maxval_shap=max([profile_shap.max(), count_shap.max()])
    return label_prof, label_sum, pred_prof, pred_sum, profile_shap, count_shap, seq, minval_perf, maxval_perf, minval_shap, maxval_shap

In [8]:
footprints=pd.read_csv("chr1.footprints.vierstra.k562.fpr0.01.bed",header=None,sep='\t')

In [9]:
footprints.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,chr1,629221,629234,.,0.01,chr1,629093,629442,.,698,.,2.35683,19.70428,17.46099,78,13
1,chr1,629221,629234,.,0.01,chr1,629093,629442,.,698,.,2.27820,18.55122,16.33244,266,13
2,chr1,629273,629310,.,0.01,chr1,629093,629442,.,698,.,2.35683,19.70428,17.46099,78,37
3,chr1,629273,629310,.,0.01,chr1,629093,629442,.,698,.,2.27820,18.55122,16.33244,266,37
4,chr1,629514,629530,.,0.01,chr1,629500,630939,.,614,.,2.12080,15.96622,13.80713,229,16

In [10]:
footprints['summit']=footprints[6]+footprints[14]

In [13]:
footprints[footprints['summit']==227902435]

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,summit
96134,chr1,227902319,227902359,.,0.01,chr1,227902352,227902681,.,729,.,4.9833,19.47339,17.23444,83,7,227902435
96136,chr1,227902392,227902409,.,0.01,chr1,227902352,227902681,.,729,.,4.9833,19.47339,17.23444,83,17,227902435
96138,chr1,227902470,227902477,.,0.01,chr1,227902352,227902681,.,729,.,4.9833,19.47339,17.23444,83,7,227902435