In [1]:
import MotifCompendium

In [2]:
#mc = MotifCompendium.load("chrombpnet_outputs/motif_compendium_average.mc", safe=True)
mc = MotifCompendium.load("chrombpnet_outputs_counts/motif_compendium.mc", safe=True)

In [3]:
import MotifCompendium.utils.analysis as utils_analysis

reference_meme = '../pipeline/data/MotifCompendium-Database-Human.meme.txt'

utils_analysis.assign_label_from_pfms(
    mc,
    reference_meme,
    save_col_prefix="refdb",
    min_score=0.5,
    max_submotifs = 2
)
mc

In [4]:
utils_analysis.assign_label_from_pfms(
    mc,
    "chrombpnet_outputs/meme_invitro_avg.meme.txt",
    save_col_prefix="chiptf",
    min_score=0.5,
    max_submotifs = 2
)

In [5]:
mc

In [12]:
print(f"Number of composite motifs: {(mc['chiptf_score0'] > 0).sum()}")

Number of composite motifs: 259

In [13]:
print(f"Number of composite motifs: {(mc['chiptf_score1'] > 0).sum()}")

Number of composite motifs: 66

In [8]:
print(f"Number of composite motifs: {(mc['refdb_score0'] == 0).sum()}")

Number of composite motifs: 32

In [9]:
print(f"Number of composite motifs: {(mc['refdb_score1'] == 0).sum()}")

Number of composite motifs: 254

In [10]:
sum((mc['refdb_score1']== 0) & (mc['chiptf_score0']==0))

32

In [11]:
mc[(mc['refdb_score1']== 0) & (mc['chiptf_score0']==0)]

In [23]:
mc.columns