In [2]:
import MotifCompendium
mc = MotifCompendium.load("motif_compendium_chip_selex_annotated.mc", safe=True)

In [18]:
print("Before filtering ..")
print("Total motifs", mc.metadata.shape[0])
print("# of pos motifs", sum(mc["posneg"] == "pos"))
print("# of neg motifs", sum(mc["posneg"] == "neg"))
print("# of profile motifs", sum(mc["model"].str.split("_",expand=True)[1] == "profile"))
print("# of counts motifs", sum(mc["model"].str.split("_",expand=True)[1] == "counts"))
# 831 motifs,

Before filtering ..
Total motifs 831
# of pos motifs 602
# of neg motifs 229
# of profile motifs 540
# of counts motifs 291

In [19]:
#mc.metadata.columns

In [33]:
df = mc[mc["model"].str.split("_",expand=True)[1] == "profile"].metadata
print("min of profle motifs:", df["model"].value_counts().min())
print("max of profle motifs:",df["model"].value_counts().max())
print("mean of profle motifs:",df["model"].value_counts().mean())
df = mc[mc["model"].str.split("_",expand=True)[1] == "counts"].metadata
print("min of count motifs:", df["model"].value_counts().min())
print("max of count motifs:",df["model"].value_counts().max())
print("mean of count motifs:",df["model"].value_counts().mean())

min of profle motifs: 71
max of profle motifs: 153
mean of profle motifs: 108.0
min of count motifs: 49
max of count motifs: 62
mean of count motifs: 58.2

In [36]:
df = mc.metadata
df["celltype"] = df["model"].str.split("_",expand=True)[0]
df["celltype"].value_counts()

celltype
GM12878    211
IMR90      188
HEPG2      171
K562       132
H1ESC      129
Name: count, dtype: int64

In [11]:

mcf = mc[mc["flag_remove"]==False]

In [17]:
print("After filtering ..")
print("Total motifs", mcf.metadata.shape[0])
print("# of pos motifs", sum(mcf["posneg"] == "pos"))
print("# of neg motifs", sum(mcf["posneg"] == "neg"))
print("# of profile motifs", sum(mcf["model"].str.split("_",expand=True)[1] == "profile"))
print("# of counts motifs", sum(mcf["model"].str.split("_",expand=True)[1] == "counts"))
# 831 motifs,

After filtering ..
Total motifs 640
# of pos motifs 484
# of neg motifs 156
# of profile motifs 416
# of counts motifs 224

In [34]:
df = mcf[mcf["model"].str.split("_",expand=True)[1] == "profile"].metadata
print("min of profle motifs:", df["model"].value_counts().min())
print("max of profle motifs:",df["model"].value_counts().max())
print("mean of profle motifs:",df["model"].value_counts().mean())
df = mcf[mcf["model"].str.split("_",expand=True)[1] == "counts"].metadata
print("min of count motifs:", df["model"].value_counts().min())
print("max of count motifs:",df["model"].value_counts().max())
print("mean of count motifs:",df["model"].value_counts().mean())

min of profle motifs: 54
max of profle motifs: 119
mean of profle motifs: 83.2
min of count motifs: 33
max of count motifs: 52
mean of count motifs: 44.8

In [38]:
df = mcf.metadata
df["celltype"] = df["model"].str.split("_",expand=True)[0]
df["celltype"].value_counts()

celltype
GM12878    166
IMR90      157
HEPG2      128
K562        99
H1ESC       90
Name: count, dtype: int64

In [43]:
print("Number of unique clusters")
len(mcf["cluster"].unique())

Number of unique clusters

400

In [45]:
unique_clusters_per_celltype = df.groupby('celltype')['cluster'].nunique()
print("Number of unique clusters per celltype")
unique_clusters_per_celltype

Number of unique clusters per celltype

celltype
GM12878    135
H1ESC       65
HEPG2       94
IMR90      124
K562        82
Name: cluster, dtype: int64

In [46]:
unique_clusters_per_head = df.groupby('posneg')['cluster'].nunique()
print("Number of unique clusters per profile/counts")
unique_clusters_per_head

Number of unique clusters per profile/counts

posneg
neg    144
pos    256
Name: cluster, dtype: int64

In [70]:
#mct = mcf[(mcf["selex_score0"]>0.9)]
#mct
mct = mcf[(mcf["selex_score0"]>0.6) & (mcf["chipdb_score1"]>0.5)]
print(mct.metadata.shape[0])

66

In [71]:
# from IPython.display import Image, display
# import base64

# for idx in range(27):
#     logo = mct.get_images('logo (fwd)')
#     image_bytes = base64.b64decode(logo[idx])
#     display(Image(data=image_bytes, format='png'))

    # logo = mct.get_images('selex_logo0')
    # image_bytes = base64.b64decode(logo[idx])
    # display(Image(data=image_bytes, format='png'))

    # logo = mct.get_images('chipdb_logo0')
    # image_bytes = base64.b64decode(logo[idx])
    # display(Image(data=image_bytes, format='png'))
    
    # print(f"Selex motif: {mct.metadata['selex_name0'][idx]}")
    # print(f"Selex score: {mct.metadata['selex_score0'][idx]}")
    # print(f"ChIP motif 0: {mct.metadata['chipdb_name0'][idx]}")
    # print(f"ChIP score 0: {mct.metadata['chipdb_score0'][idx]}")
    # print(f"ChIP motif 1: {mct.metadata['chipdb_name1'][idx]}")
    # print(f"ChIP score 1: {mct.metadata['chipdb_score1'][idx]}")

In [72]:
mct

In [74]:
mc_chip = MotifCompendium.load("/oak/stanford/groups/akundaje/cmyun/motifcompendium/tfatlas/encode_qc/pipeline/counts/pipeline_counts_0.88-rec-force0.92-v2/motifcompendium_cluster_labeled.mc", safe=True)


mc_chip["label"]=mc_chip["target"]+"add"+mc_chip["family"]+'add'+mc_chip["MotifCompendium-Database-Human.meme_name0"]+'add'+mc_chip["reference_name0"]

In [83]:
#mct.columns()
df = mc_chip.metadata[['name', 'label']]

In [86]:
newmct = mct.metadata.merge(df, right_on="name", left_on="chipdb_name1")

In [87]:
newmct['label']

0     BCL11A,CTCF,MLXIP,PRDM6,RARB,TP53,ZFP37,ZNF337...
1                                    ZNF600addZNFaddadd
2          ZNF184addZNFaddZNF184addJASP.MA2120.1.ZNF184
3     ARNT,ATF2,BATF,BCL11A,BHLHE40,BMI1,CBFB,CREB1,...
4     ATF1,ATF2,BATF,BCL11A,BCL3,BHLHE40,CBFB,CREB1,...
                            ...
61                  NR3C1addNR3CaddaddJASP.MA0476.2.FOS
62    GATA2,REST,ZNF12,ZNF276,ZNF280B,ZNF44,ZNF485,Z...
63    FOXA3addFOXaddGATA1,GATA2,GATA3,GATA4,GATA5,GA...
64                                    CTCFaddCTCFaddadd
65                            ZNF33B,ZNF547addZNFaddadd
Name: label, Length: 66, dtype: object

In [88]:
newmct

,name_x,num_seqlets,model,posneg,avg_contrib,avg_dist_from_summit,cluster,selex_score0,selex_name0,chipdb_score0,...,copair_composition,dinuc_entropy_score,dinuc_composition,dinuc_score,posneg_inverted,truncated,flag_remove,celltype,name_y,label
0,GM12878_counts-pos.pattern_23,1175,GM12878_counts,pos,0.579994,52.781277,410,0.750100,CAPSLX.ETV4::IRF8.0,0.841278,...,0.179852,0.316264,0.600709,0.200999,False,False,False,GM12878,cpm_leiden_0.88-rec-force0.92#60,"BCL11A,CTCF,MLXIP,PRDM6,RARB,TP53,ZFP37,ZNF337..."
1,GM12878_counts-pos.pattern_26,980,GM12878_counts,pos,0.520586,56.747959,102,0.807392,CAPSLX.HOXD12::IRF7.0,0.816434,...,0.141529,0.388359,0.573447,0.235124,False,False,False,GM12878,cpm_leiden_0.88-rec-force0.92#376,ZNF600addZNFaddadd
2,GM12878_counts-pos.pattern_33,201,GM12878_counts,pos,0.653088,44.935323,419,0.839936,CAPSLX.ELF2::IRF7.0,0.789984,...,0.114289,0.319863,0.604525,0.233041,False,False,False,GM12878,cpm_leiden_0.88-rec-force0.92#343,ZNF184addZNFaddZNF184addJASP.MA2120.1.ZNF184
3,GM12878_counts-pos.pattern_36,168,GM12878_counts,pos,0.502060,51.327381,413,0.698385,CAPSLX.HMX3::RUNX2.0,0.894206,...,0.081300,0.321037,0.573579,0.286585,False,False,False,GM12878,cpm_leiden_0.88-rec-force0.92#34,"ARNT,ATF2,BATF,BCL11A,BHLHE40,BMI1,CBFB,CREB1,..."
4,GM12878_counts-pos.pattern_37,147,GM12878_counts,pos,0.404381,45.850340,412,0.750916,CAPSLX.ETV4::GCM1.0,0.862193,...,0.097601,0.296856,0.527198,0.148052,False,False,False,GM12878,cpm_leiden_0.88-rec-force0.92#5,"ATF1,ATF2,BATF,BCL11A,BCL3,BHLHE40,CBFB,CREB1,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,H1ESC_profile-pos.pattern_35,134,H1ESC_profile,pos,0.051477,71.656716,79,0.736374,CAPSLX.POU2F3::SOX11.1,0.816243,...,0.067449,0.250688,0.458840,0.211952,False,False,False,H1ESC,cpm_leiden_0.88-rec-force0.92#699,NR3C1addNR3CaddaddJASP.MA0476.2.FOS
62,H1ESC_profile-pos.pattern_38,102,H1ESC_profile,pos,0.048023,56.107843,43,0.699290,CAPSLX.ETV1::TEAD4.1,0.842813,...,0.081174,0.233785,0.405448,0.144781,False,False,False,H1ESC,cpm_leiden_0.88-rec-force0.92#100,"GATA2,REST,ZNF12,ZNF276,ZNF280B,ZNF44,ZNF485,Z..."
63,H1ESC_profile-neg.pattern_15,106,H1ESC_profile,neg,-0.018216,72.943396,265,0.739418,CAPSLX.IRX5::HOXA2.0,0.768535,...,0.262742,0.188185,0.537853,0.385228,False,False,False,H1ESC,cpm_leiden_0.88-rec-force0.92#661,"FOXA3addFOXaddGATA1,GATA2,GATA3,GATA4,GATA5,GA..."
64,H1ESC_profile-neg.pattern_8,137,H1ESC_profile,neg,0.016568,58.036496,347,0.664061,CAPSLX.ATOH1::POU2F2.0,0.798498,...,0.266100,0.173652,0.564711,0.349863,False,False,False,H1ESC,cpm_leiden_0.88-rec-force0.92#189,CTCFaddCTCFaddadd
65,H1ESC_profile-neg.pattern_9,132,H1ESC_profile,neg,-0.024847,78.477273,415,0.708984,CAPSLX.SHOX::MEF2D.0,0.833211,...,0.284851,0.222444,0.551968,0.412438,False,False,False,H1ESC,cpm_leiden_0.88-rec-force0.92#372,"ZNF33B,ZNF547addZNFaddadd"